---
title: "scenario_2040"
author: "Teague Tran"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
raster_2020<-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1050_0.tif"))
raster_2020s6<-  read_stars(here("data", "cwhr_MIROC5_85_Scenario6_v3_20210820_1301_0.tif"))
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210824_1050_20.tif"))
```

```{r}
#function to merge the two rasters
merge_function <- function(lulc_2020, lulc_2040) {
  added_rasters <- lulc_2020*10000 + lulc_2040 # add rasters together
  added_vectorized <- st_as_sf(added_rasters) #vectorize added rasters
  colnames(added_vectorized) <- c("gridcodes", "geometry") #change column names
  added_vectorized$gridcodes <-sprintf('%08d', added_vectorized$gridcodes) #make the gridcodes column easier tove parse out
  merged <- mutate(added_vectorized, gridcode_2020 = substr(added_vectorized$gridcodes, 1, 4)) %>% #create merged dataframe where we can look at forest type and canopy cover
    mutate(added_vectorized, gridcode_2040 = substr(added_vectorized$gridcodes, 5, 8)) %>% 
    mutate(forest_type_2020 = substr(gridcode_2020, 1, nchar(gridcode_2020)-2)) %>% #create forest type column for 2020 and 2040
    mutate(canopy_cover_2020 = as.numeric(gridcode_2020) %% 10) %>% 
    mutate(forest_type_2040 = substr(gridcode_2040, 1, nchar(gridcode_2040)-2)) %>% #create canopy cover column for 2020 and 2040 
    mutate(canopy_cover_2040 = as.numeric(gridcode_2040) %% 10) %>% 
    mutate(forest_diff = as.numeric(forest_type_2040) - as.numeric(forest_type_2020)) %>% #subtract canopy cover and forest type columns for 2020 and 2040
    mutate(canopy_diff = canopy_cover_2040 - canopy_cover_2020) %>% 
    mutate(cell_diff = ifelse(as.numeric(canopy_diff) == 0 & as.numeric(forest_diff) == 0, 0, 1)) #create new column where no change = 0 and ANY change = 1 
}

```

```{r}

#first 2040 raster 1
output <- merge_function(raster_2020, raster_2040)
diff_sum <- sum(output$cell_diff)

#load another 2040 raster 2
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210824_1051_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)


#load another 2040 raster 3
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210824_1052_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new) #this is the max

#load another 2040 raster 4
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210824_1053_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 5
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210824_1054_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 6
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210824_1057_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 7
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210825_1255_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 8 
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210825_1257_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 9
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210825_1259_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 10
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210825_1302_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 11
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210825_1304_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 12
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210825_1446_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 13
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210825_1448_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 14
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210826_1934_20.tif")) #maximum for 2040 scen 1
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 15
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210826_1935_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 16
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210826_1951_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 17
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210826_1957_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 18
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210826_1958_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 19
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210826_2000_20.tif")) #minimum for 2040 scen 1
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new) 

#load another 2040 raster 20
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210827_1747_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 21
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210827_1748_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 22
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210828_1644_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 23
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210828_1646_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2040 raster 24
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario1_v3_20210828_1648_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

```



```{r}
max(diff_sum)
min(diff_sum)
```

```{r}

#load another 2040 raster 1
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210820_1301_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6 <- sum(output$cell_diff)

#load another 2040 raster 2
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210820_1302_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 3
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210820_1303_20.tif")) 
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 4
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210820_1306_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 5
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210820_1307_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 6
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210820_1308_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 7
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210820_1309_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 8
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210821_1212_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 9
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210821_1213_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 10
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210821_1214_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 11
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210821_1215_20.tif")) #minimum for 2040 scen 6
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 12
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210821_1217_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 13
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210821_1218_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 14
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210821_1219_20.tif")) #maximum for 2040 scen 6
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 15 
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210822_2123_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 16
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210822_2124_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 17
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210822_2125_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 18
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210822_2127_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 19
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210822_2128_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 20
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210827_1746_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 21
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210828_1645_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 22
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210828_1646_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)

#load another 2040 raster 23
raster_2040 <-  read_stars(here("data","2040", "cwhr_MIROC5_85_Scenario6_v3_20210828_1648_20.tif"))
#perform function
output <- merge_function(raster_2020, raster_2040)
diff_sum_2040s6_new <- sum(output$cell_diff)
diff_sum_2040s6 <- rbind(diff_sum_2040s6, diff_sum_2040s6_new)
```

```{r}
max(diff_sum_2040s6)
min(diff_sum_2040s6)
```



