---
title: "scenario_diff_usethis"
author: "Teague Tran"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
raster_2020<-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1050_0.tif"))
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210824_1050_40.tif"))
```

```{r}
#function to merge the two rasters
merge_function <- function(lulc_2020, lulc_2060) {
  added_rasters <- lulc_2020*10000 + lulc_2060 # add rasters together
  added_vectorized <- st_as_sf(added_rasters) #vectorize added rasters
  colnames(added_vectorized) <- c("gridcodes", "geometry") #change column names
  added_vectorized$gridcodes <-sprintf('%08d', added_vectorized$gridcodes) #make the gridcodes column easier tove parse out
  merged <- mutate(added_vectorized, gridcode_2020 = substr(added_vectorized$gridcodes, 1, 4)) %>% #create merged dataframe where we can look at forest type and canopy cover
    mutate(added_vectorized, gridcode_2060 = substr(added_vectorized$gridcodes, 5, 8)) %>% 
    mutate(forest_type_2020 = substr(gridcode_2020, 1, nchar(gridcode_2020)-2)) %>% #create forest type column for 2020 and 2060
    mutate(canopy_cover_2020 = as.numeric(gridcode_2020) %% 10) %>% 
    mutate(forest_type_2060 = substr(gridcode_2060, 1, nchar(gridcode_2060)-2)) %>% #create canopy cover column for 2020 and 2060 
    mutate(canopy_cover_2060 = as.numeric(gridcode_2060) %% 10) %>% 
    mutate(forest_diff = as.numeric(forest_type_2060) - as.numeric(forest_type_2020)) %>% #subtract canopy cover and forest type columns for 2020 and 2060
    mutate(canopy_diff = canopy_cover_2060 - canopy_cover_2020) %>% 
    mutate(cell_diff = ifelse(as.numeric(canopy_diff) == 0 & as.numeric(forest_diff) == 0, 0, 1)) #create new column where no change = 0 and ANY change = 1 
}

```

```{r}
#first 2060 raster 1
output <- merge_function(raster_2020, raster_2060)
diff_sum <- sum(output$cell_diff)

#load another 2060 raster 2
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210824_1051_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)


#load another 2060 raster 3
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210824_1052_40.tif")) # max for 2060 scen 1
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new) 

#load another 2060 raster 4
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210824_1053_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 5
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210824_1054_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 6
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210824_1057_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 7
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210825_1255_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 8 
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210825_1257_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 9
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210825_1259_40.tif")) # min for 2060 scen 1
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 10
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210825_1302_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 11
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210825_1304_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 12
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210825_1446_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 13
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210825_1448_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 14
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210826_1934_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 15
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210826_1935_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 16
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210826_1951_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 17
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210826_1957_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 18
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210826_1958_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 19
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210826_2000_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 20
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210827_1747_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 21
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210827_1748_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 22
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210828_1644_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 23
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210828_1646_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

#load another 2060 raster 24
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario1_v3_20210828_1648_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_new <- sum(output$cell_diff)
diff_sum <- rbind(diff_sum, diff_sum_new)

```

```{r}
max(diff_sum)
min(diff_sum)
```

```{r}
#load another 2060 raster 1
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210820_1301_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6 <- sum(output$cell_diff)


#load another 2060 raster 2
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210820_1302_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 3
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210820_1303_40.tif")) # this is the minimum for 2060 s6
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 4
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210820_1306_40.tif")) # this is the maximum for 2060 s6
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 5
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210820_1307_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 6
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210820_1308_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 7
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210820_1309_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 8
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210821_1212_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 9
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210821_1213_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 10
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210821_1214_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 11
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210821_1215_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 12
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210821_1217_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 13
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210821_1218_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 14
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210821_1219_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 15 
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210822_2123_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 16
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210822_2124_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 17
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210822_2125_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 18
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210822_2127_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 19
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210822_2128_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 20
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210827_1746_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 21
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210828_1645_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 22
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210828_1646_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)

#load another 2060 raster 23
raster_2060 <-  read_stars(here("data","2060", "cwhr_MIROC5_85_Scenario6_v3_20210828_1648_40.tif"))
#perform function
output <- merge_function(raster_2020, raster_2060)
diff_sum_2060s6_new <- sum(output$cell_diff)
diff_sum_2060s6 <- rbind(diff_sum_2060s6, diff_sum_2060s6_new)
```

```{r}
max(diff_sum_2060s6)
min(diff_sum_2060s6)
```

































```{r}
#parse out code to make forest type and canopy cover column for 2020 and 2060 and then subtract
lulc_parse <- function(merged) {
  merged <- merged %>% 
  mutate(forest_type_2020 = substr(gridcode_2020, 1, nchar(gridcode_2020)-2)) %>% #create forest type column for 2020 and 2060
  mutate(canopy_cover_2020 = as.numeric(gridcode_2020) %% 10) %>% 
  mutate(forest_type_2060 = substr(gridcode_2060, 1, nchar(gridcode_2060)-2)) %>% #create canopy cover column for 2020 and 2060 
  mutate(canopy_cover_2060 = as.numeric(gridcode_2060) %% 10) %>% 
  mutate(forest_diff = as.numeric(forest_type_2060) - as.numeric(forest_type_2020)) %>% #subtract canopy cover and forest type columns for 2020 and 2060
  mutate(canopy_diff = canopy_cover_2060 - canopy_cover_2020) %>% 
  mutate(cell_diff = ifelse(as.numeric(canopy_diff) == 0 & as.numeric(forest_diff) == 0, 0, 1)) #create new column where no change = 0 and ANY change = 1 
}
```

```{r}
landuse <- merge
```







```{r}
#Niklas's code
# merged = scenario_raster_scenario1_2020*10000  + scenario_raster_scenario1_2060
# merged = st_as_sf(merged)
# colnames(merged) <- c("gridcodes", "geometry")
# merged$gridcodes = sprintf('%08d', merged$gridcodes)
# merged = mutate(merged, gridcode_2020 = substr(merged$gridcodes, 1, 4))
# merged = mutate(merged, gridcode_2060 = substr(merged$gridcodes, 5, 8))

```

```{r}
#parse out code for "new" column
merged_lulc <- merged %>% 
  mutate(forest_type_2020 = substr(gridcode_2020, 1, nchar(gridcode_2020)-2)) %>% 
  mutate(canopy_cover_2020 = as.numeric(gridcode_2020) %% 10) %>% 
  mutate(forest_type_2060 = substr(gridcode_2060, 1, nchar(gridcode_2060)-2)) %>% 
  mutate(canopy_cover_2060 = as.numeric(gridcode_2060) %% 10) %>% 
  mutate(forest_diff = as.numeric(forest_type_2060) - as.numeric(forest_type_2020)) %>% 
  mutate(canopy_diff = canopy_cover_2060 - canopy_cover_2020) %>% 
  mutate(cell_diff = ifelse(as.numeric(canopy_diff) == 0 & as.numeric(forest_diff) == 0, 0, 1))







lulc_num <- function(lulc_select) {
  lulc_sep <- lulc_select %>% 
    mutate(last_2 = lulc_select$gridcode %% 100) %>%
    mutate(first_two = substr(lulc_select$gridcode, 1, nchar(lulc_select$gridcode)-2 )) 
  
#separate the number in the gridcode to create new columns
  lulc_sep <- lulc_sep %>% 
    mutate(second_last = substr(lulc_sep$last_2, 1, 1) ) %>% 
    mutate(first_last = lulc_select$gridcode %% 10) %>% 
    mutate(forest_type = first_two) %>% 
    mutate(seral_stage = second_last) %>% 
    mutate(canopy_cover = first_last) %>% 
    mutate(ecoregion_type = as.numeric(forest_type))
}
```
